/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LoginRouteImport } from './app/login'
import { Route as AuthedRouteImport } from './app/_authed'
import { Route as AuthedIndexRouteImport } from './app/_authed/index'
import { Route as AuthCallbackRouteImport } from './app/auth.callback'
import { Route as AuthedWaitlistRouteImport } from './app/_authed/waitlist'
import { Route as AuthedSearchRouteImport } from './app/_authed/search'
import { Route as AuthedNotificationsRouteImport } from './app/_authed/notifications'
import { Route as AuthedEditProfileRouteImport } from './app/_authed/edit-profile'
import { Route as AuthedCreateRouteImport } from './app/_authed/create'
import { Route as AuthedUsernameRouteImport } from './app/_authed/$username'
import { Route as ApiAuthSplatRouteImport } from './app/api.auth.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWaitlistRoute = AuthedWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEditProfileRoute = AuthedEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsernameRoute = AuthedUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/$username': typeof AuthedUsernameRoute
  '/create': typeof AuthedCreateRoute
  '/edit-profile': typeof AuthedEditProfileRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/search': typeof AuthedSearchRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$username': typeof AuthedUsernameRoute
  '/create': typeof AuthedCreateRoute
  '/edit-profile': typeof AuthedEditProfileRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/search': typeof AuthedSearchRoute
  '/waitlist': typeof AuthedWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$username': typeof AuthedUsernameRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/_authed/edit-profile': typeof AuthedEditProfileRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/waitlist': typeof AuthedWaitlistRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$username'
    | '/create'
    | '/edit-profile'
    | '/notifications'
    | '/search'
    | '/waitlist'
    | '/auth/callback'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$username'
    | '/create'
    | '/edit-profile'
    | '/notifications'
    | '/search'
    | '/waitlist'
    | '/auth/callback'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/$username'
    | '/_authed/create'
    | '/_authed/edit-profile'
    | '/_authed/notifications'
    | '/_authed/search'
    | '/_authed/waitlist'
    | '/auth/callback'
    | '/_authed/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/waitlist': {
      id: '/_authed/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof AuthedWaitlistRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/edit-profile': {
      id: '/_authed/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthedEditProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$username': {
      id: '/_authed/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof AuthedUsernameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedUsernameRoute: typeof AuthedUsernameRoute
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedEditProfileRoute: typeof AuthedEditProfileRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedWaitlistRoute: typeof AuthedWaitlistRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUsernameRoute: AuthedUsernameRoute,
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedEditProfileRoute: AuthedEditProfileRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedWaitlistRoute: AuthedWaitlistRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
