export const PLACE_AUTOCOMPLETE_INPUT_MIN_LENGTH = 3;
export const PLACE_AUTOCOMPLETE_INPUT_MAX_LENGTH = 120;
export const PLACE_SESSION_TOKEN_MAX_LENGTH = 128;
export const PLACE_ID_MAX_LENGTH = 256;
export const PLACE_NAME_MAX_LENGTH = 160;
export const PLACE_FORMATTED_ADDRESS_MAX_LENGTH = 280;
export const PLACE_AUTOCOMPLETE_LIMIT = 5;

export const PLACE_MIN_LATITUDE = -90;
export const PLACE_MAX_LATITUDE = 90;
export const PLACE_MIN_LONGITUDE = -180;
export const PLACE_MAX_LONGITUDE = 180;
